import { existsSync, readFileSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
// Store all markdown sources
const markdownSources = {};
export const copyPagePlugin = (options = {}) => ({
    name: 'vuepress-plugin-copy-page',
    // Read markdown source for each page
    extendsPage(page) {
        const filePath = page.filePath;
        if (filePath && existsSync(filePath)) {
            const content = readFileSync(filePath, 'utf-8');
            markdownSources[page.path] = content;
        }
    },
    // Generate client config file to inject data
    clientConfigFile(app) {
        const finalOptions = {
            includes: options.includes ?? ['/posts/'],
            excludes: options.excludes ?? [],
            position: options.position ?? 'top-right',
        };
        const content = `// Auto-generated by vuepress-plugin-copy-page
if (typeof window !== 'undefined') {
  window.__COPY_PAGE_OPTIONS__ = ${JSON.stringify(finalOptions)}
  window.__MARKDOWN_SOURCES__ = ${JSON.stringify(markdownSources)}
}
`;
        // Write to temp directory
        const tempDir = app.dir.temp();
        const configDir = join(tempDir, 'copy-page');
        const tempPath = join(configDir, 'data.js');
        if (!existsSync(configDir)) {
            mkdirSync(configDir, { recursive: true });
        }
        writeFileSync(tempPath, content, 'utf-8');
        return tempPath;
    },
});
export default copyPagePlugin;
