import type { Plugin, App, Page } from 'vuepress'
import { existsSync, readFileSync, mkdirSync, writeFileSync } from 'fs'
import { join } from 'path'

export interface CopyPageOptions {
  /**
   * Page path patterns where the copy button should appear
   * @default ['/posts/']
   */
  includes?: string[]

  /**
   * Page path patterns where the copy button should NOT appear
   * @default []
   */
  excludes?: string[]

  /**
   * Position of the copy button
   * @default 'top-right'
   */
  position?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left'
}

// Store all markdown sources
const markdownSources: Record<string, string> = {}

export const copyPagePlugin = (options: CopyPageOptions = {}): Plugin => ({
  name: 'vuepress-plugin-copy-page',

  // Read markdown source for each page
  extendsPage(page: Page): void {
    const filePath = page.filePath
    if (filePath && existsSync(filePath)) {
      const content = readFileSync(filePath, 'utf-8')
      markdownSources[page.path] = content
    }
  },

  // Generate client config file to inject data
  clientConfigFile(app: App): string {
    const finalOptions = {
      includes: options.includes ?? ['/posts/'],
      excludes: options.excludes ?? [],
      position: options.position ?? 'top-right',
    }

    const content = `// Auto-generated by vuepress-plugin-copy-page
if (typeof window !== 'undefined') {
  window.__COPY_PAGE_OPTIONS__ = ${JSON.stringify(finalOptions)}
  window.__MARKDOWN_SOURCES__ = ${JSON.stringify(markdownSources)}
}
`

    // Write to temp directory
    const tempDir = app.dir.temp()
    const configDir = join(tempDir, 'copy-page')
    const tempPath = join(configDir, 'data.js')

    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true })
    }
    writeFileSync(tempPath, content, 'utf-8')

    return tempPath
  },
})

export default copyPagePlugin
